# Generated by Django 2.0 on 2017-12-27 23:24

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('isp', models.CharField(max_length=300)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoreServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.FloatField()),
                ('upload', models.FloatField()),
                ('ping', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('bytes_sent', models.IntegerField()),
                ('bytes_received', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testspeed.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.ManyToManyField(to='testspeed.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(null=True, unique=True)),
                ('url', models.CharField(max_length=500)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('sponsor', models.CharField(max_length=500)),
                ('host', models.CharField(max_length=500)),
                ('d', models.FloatField()),
                ('latency', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testspeed.Server'),
        ),
        migrations.AddField(
            model_name='ignoreservers',
            name='servers',
            field=models.ManyToManyField(to='testspeed.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('ip', 'isp')},
        ),
    ]
