# Generated by Django 2.0 on 2018-01-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testspeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ignoreservers',
            name='servers',
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='identifier',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IgnoreServers',
        ),
    ]
