# Generated by Django 2.0 on 2017-12-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testspeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='longitude',
            new_name='lon',
        ),
    ]
