# Generated by Django 2.0 on 2017-12-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testspeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='identifier',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
